name: Build service

on:
  push:
    branches:
      - main
    paths:
      - '/'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:

          username: ${{ secrets.STEKOLSHCHYKOV_DOCKER_USERNAME }}
          password: ${{ secrets.STEKOLSHCHYKOV_DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.STEKOLSHCHYKOV_DOCKER_USERNAME }}/geo-service:latest
